/*
 * Author: Devin McDermott
 * Adventure Camp Med Tracker
 * April 2021
 */

package org.example;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.scene.control.DatePicker;
import javafx.scene.control.TextField;
import java.io.IOException;
import java.sql.*;

// controller class for add_camper.fxml
public class ControllerAddCamper {

    ObservableList<Camper> oblist = FXCollections.observableArrayList();

    public TextField tfLastName;
    public TextField tfFirstName;
    public DatePicker dpDOB;
    public TextField tfGuardian;
    public TextField tfContact;
    public TextField tfNote;
    public static int currentCamperID;

    // add a new camper
    @FXML
    private void addCamper() throws IOException {

        try (Connection con = DBDriver.getConnection()) {

            // sql query insert new camper
            String query = " insert into campers (last_name, first_name, dob, guardian, contact, note)"
                    + " values (?, ?, ?, ?, ?, ?)";

            // create sql prepared statement
            PreparedStatement preparedStmt = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            preparedStmt.setString (1, tfLastName.getText());
            preparedStmt.setString (2, tfFirstName.getText());
            preparedStmt.setString (3, dpDOB.getValue().toString());
            preparedStmt.setString (4, tfGuardian.getText());
            preparedStmt.setString (5, tfContact.getText());
            preparedStmt.setString (6, tfNote.getText());

            // execute the prepared statement
            preparedStmt.execute();

            // update the campers table
            ResultSet rs = con.createStatement().executeQuery("select * from campers");
            while (rs.next()) {
                oblist.add(new Camper(
                        rs.getInt("id"),
                        rs.getString("last_name"),
                        rs.getString("first_name"),
                        rs.getString("dob"),
                        rs.getString("guardian"),
                        rs.getString("contact"),
                        rs.getString("note")));
            }

            // get new camper's id generated by the db
            ResultSet rs2 =preparedStmt.getGeneratedKeys();
            if (rs2.next()) {
                currentCamperID = rs2.getInt(1);
            }

            // after adding new camper, navigate to add prescriptions
            App.setRoot("add_prescriptions");
        }
        catch (SQLException throwables) {
            throwables.printStackTrace();
        }

    }

    // when the cancel button is clicked, navigate to dashboard
    @FXML
    private void switchToDashboard() throws IOException {
        App.setRoot("dashboard");
    }
}
